const MAX_SOURCE_CHARS = 64 * 1024;
const MAX_STDIN_CHARS = 16 * 1024;
const MIN_REQUEST_INTERVAL_MS = 1200;
const CPU_TIME_LIMIT_SEC = 5;
const WALL_TIME_LIMIT_SEC = 10;
const MEMORY_LIMIT_KB = 128000;
const POLL_TIMEOUT_MS = 20000;

module.exports = {
  MAX_SOURCE_CHARS,
  MAX_STDIN_CHARS,
  MIN_REQUEST_INTERVAL_MS,
  CPU_TIME_LIMIT_SEC,
  WALL_TIME_LIMIT_SEC,
  MEMORY_LIMIT_KB,
  POLL_TIMEOUT_MS,
};
